version: '3.1'
services:

  redis-public-ui:
    image: 'redis:7.2'
    networks:
      - hmpps
    container_name: redis-public-ui
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0

  app:
    build: .
    networks:
      - hmpps
    depends_on: [redis-public-ui]
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis-public-ui
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      # These will need to match new creds in the seed auth service auth
      - SYSTEM_CLIENT_ID=system-client-id
      - SYSTEM_CLIENT_SECRET=system-client-secret

networks:
  hmpps:
